export {default as Navbar} from './shared/Navbar';
export {default as Header} from './Home/Header';
export {default as Hiw} from './Home/Hiw';
export {default as Footer} from './shared/Footer';
export {default as ApplyForTutor} from './apply-for-tutor/BecomeTutor'
export {default as Features} from './Home/Features';
export {default as Goal} from './Home/Goal'
export {default as Availability} from './tutorpage/Availability'
export {default as Reviews} from './tutorpage/Reviews'
export {default as Ratings} from './tutorpage/Ratings'